version: '3'

services:

  cart-postgres:
    image: "postgres:9.6-alpine"
    container_name: cart-postgres
    ports:
      - 5432:5432

    environment:
      - POSTGRES_DB=cart
      - POSTGRES_USER=cart
      - POSTGRES_PASSWORD=cart

  cart-app:
    build: ./
    container_name: cart-app

    environment:
      - DB_SERVER=cart-postgres
      - POSTGRES_DB=cart
      - POSTGRES_USER=cart
      - POSTGRES_PASSWORD=cart
    ports:
      - 8080:8080
    links:
      - cart-postgres